apiVersion: v1
kind: Service
metadata:
  name: {{ include "conan-exiles-server.fullname" . }}
  labels:
    {{- include "conan-exiles-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gameport
      port: {{ .Values.service.gameport }}
      targetPort: 7777
      protocol: UDP
    - name: gameport2
      port: 7778
      targetPort: 7778
      protocol: UDP
    - name: gameport3
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: conan-tcp
      port: 7777
      targetPort: 7777
      protocol: TCP
    - name: rconport
      port: 25575
      targetPort: 25575
      protocol: TCP
    
  selector:
    {{- include "conan-exiles-server.selectorLabels" . | nindent 4 }}
