# Base Dockerfile
FROM {{.BaseDockerfile}}

# Set game name
LABEL server="{{.EnvironmentName}}"

# Set type
LABEL type="{{.Type}}"
{{if eq .Type "steam"}}
# Steam App ID
LABEL steam_app_id="{{.SteamAppID}}"
{{end}}
# Set Maintainer
LABEL maintainer="{{.Maintainer}}"
{{if .AdditionalDeps}}
# Install dependencies
RUN apt update && apt upgrade -y && \
    apt install --no-install-recommends --no-install-suggests -y \
    {{range $index, $dep := .AdditionalDeps}}{{if $index}} \
    {{end}}{{$dep}}{{end}}

RUN apt remove --purge -y curl && \
    apt autoremove -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{{end}}
# Copy server config template to protected location (not overwritten by PVC mounts)
COPY images/bin/{{ .EnvironmentName }}/serverconfig.template /usr/local/share/game-templates/serverconfig.template

RUN mkdir -p /home/kubelize/config-data && \
    chown -R kubelize:kubelize /home/kubelize/server /home/kubelize/config-data

WORKDIR /home/kubelize/server
USER kubelize

ENTRYPOINT ["gamekeeper", "start", "--game", "{{.EnvironmentName}}"]
