apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-servers.fullname" . }}-game
  labels:
    {{- include "game-servers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gameService.type }}
  ports:
    {{- range .Values.gameService.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "game-servers.selectorLabels" . | nindent 4 }}