{{- if not .Values.serverPasswordSecret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "game-servers.fullname" . }}-server-password
  labels:
    {{- include "game-servers.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  ServerPassword: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}