{{- if not .Values.serverPasswordSecret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "game-servers.fullname" . }}-server-password
  labels:
    {{- include "game-servers.labels" . | nindent 4 }}
type: Opaque
data:
  serverpassword.yaml: {{ printf "ServerPassword: %s\nWebUIPassword: %s" (randAlphaNum 16) (randAlphaNum 16) | b64enc | quote }}
{{- end }}
